import { getFirebaseRuntime } from "../config/firebase";
import { readAssignment, type Assignment, type BusConfig, validCoordinate } from "./fleet";
export interface DriverProfile { enabled?: boolean; displayName?: string; email?: string; }
export interface DriverLocation { latitude:number; longitude:number; accuracyMeters:number; speedMps?:number; headingDeg?:number; capturedAt:number; }
export interface DriverTrackingSession { busId:string; stop:()=>Promise<void>; }
export const getLocationSupportMessage=()=>!window.isSecureContext?"Location requires HTTPS (or localhost).":!("geolocation" in navigator)?"This browser does not support geolocation.":"";
const options: PositionOptions={enableHighAccuracy:true,maximumAge:1_000,timeout:20_000};
function message(error: GeolocationPositionError) { switch(error.code){case error.PERMISSION_DENIED:return "Location permission was denied by the browser.";case error.POSITION_UNAVAILABLE:return "Your device cannot currently determine a location.";case error.TIMEOUT:return "The location request timed out. Try again outdoors.";default:return error.message||"Could not get your location.";} }
function location(p:GeolocationPosition):DriverLocation { const {latitude,longitude,accuracy,speed,heading}=p.coords; if(!validCoordinate(latitude,longitude)) throw new Error("The browser returned invalid GPS coordinates."); return {latitude,longitude,accuracyMeters:Number.isFinite(accuracy)?Math.max(0,accuracy):0,speedMps:typeof speed==="number"&&Number.isFinite(speed)?speed:undefined,headingDeg:typeof heading==="number"&&Number.isFinite(heading)?heading:undefined,capturedAt:p.timestamp}; }
function firstFix(){return new Promise<DriverLocation>((resolve,reject)=>{const id=navigator.geolocation.watchPosition(p=>{navigator.geolocation.clearWatch(id);resolve(location(p));},e=>{navigator.geolocation.clearWatch(id);reject(new Error(message(e)));},options);});}
export async function signInDriver(email:string,password:string){const r=await getFirebaseRuntime();return r.signInWithEmailAndPassword(r.auth,email,password);}
export async function signOutDriver(){const r=await getFirebaseRuntime();await r.signOut(r.auth);}
export async function loadDriverProfile(uid:string){const r=await getFirebaseRuntime(),s=await r.get(r.ref(r.db,`drivers/${uid}`));return s.exists()?s.val() as DriverProfile:null;}
export async function saveDriverName(uid:string,displayName:string,email?:string){const name=displayName.trim();if(name.length<2||name.length>100)throw new Error("Enter your full name (2–100 characters).");const r=await getFirebaseRuntime();await r.update(r.ref(r.db,`drivers/${uid}`),{displayName:name,...(email?{email}:{}),updatedAt:r.serverTimestamp()});}
export async function getDriverAssignment(uid:string){return readAssignment(uid);}
function inside(point: DriverLocation, polygon: unknown): boolean { if (!Array.isArray(polygon)) return false; let hit=false; for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if(!Array.isArray(a)||!Array.isArray(b)||!validCoordinate(a[1],a[0])||!validCoordinate(b[1],b[0]))return false;const cross=((a[1]>point.latitude)!==(b[1]>point.latitude))&&(point.longitude<(b[0]-a[0])*(point.latitude-a[1])/(b[1]-a[1])+a[0]);if(cross)hit=!hit;} return hit; }
/** Spark-compatible, client-side geofence transition recorder. Initial state never creates an event. */
async function processGeofences(r: Awaited<ReturnType<typeof getFirebaseRuntime>>, busId:string, point:DriverLocation) { const all=await r.get(r.ref(r.db,"geofences")); const fences=all.val() as Record<string,{enabled?:boolean;points?:unknown;trigger?:string;cooldownSeconds?:number;publicNotification?:boolean;message?:string}>|null; if(!fences)return; for(const [id,f] of Object.entries(fences)){if(f.enabled===false)continue;const stateRef=r.ref(r.db,`geofenceState/${busId}/${id}`), old=(await r.get(stateRef)).val() as {inside?:boolean;lastEventAt?:number}|null, isInside=inside(point,f.points);if(!old){await r.set(stateRef,{inside:isInside,updatedAt:r.serverTimestamp()});continue;}const eventType=isInside===old.inside?null:isInside?"enter":"exit";const cooldown=(f.cooldownSeconds??300)*1000;if(eventType&&(f.trigger==="both"||f.trigger===eventType)&&Date.now()-(old.lastEventAt??0)>=cooldown){const key=r.push(r.ref(r.db,"geofenceEvents")).key as string;const event={busId,geofenceId:id,type:eventType,message:f.message??"",occurredAt:r.serverTimestamp()};await r.update(r.ref(r.db,"/"),{[`geofenceEvents/${key}`]:event,[`geofenceState/${busId}/${id}`]:{inside:isInside,lastEventAt:r.serverTimestamp(),updatedAt:r.serverTimestamp()},...(f.publicNotification?{[`publicNotifications/${key}`]:event}:{})});}else await r.update(stateRef,{inside:isInside,updatedAt:r.serverTimestamp()});} }
/** Client-side tracking is intentional: Spark plans cannot run Cloud Functions. Rules limit writes, but GPS/geofence data is not server-authoritative. */
export async function startDriverTracking(bus:BusConfig, assignment:Assignment, onPosition:(p:DriverLocation)=>void,onError:(m:string)=>void):Promise<DriverTrackingSession>{
 const support=getLocationSupportMessage();if(support)throw new Error(support);
 // Must be the first async work after Start Tracking's click: native browser GPS request.
 const initial=await firstFix();onPosition(initial);
 const r=await getFirebaseRuntime(),user=r.auth.currentUser;if(!user)throw new Error("Sign in before tracking.");
 const current=await readAssignment(user.uid);if(!current||current.busId!==assignment.busId)throw new Error("Your assignment changed. Ask an administrator before tracking.");
 const lock=r.ref(r.db,`activeDrivers/${bus.id}`), publicLive=r.ref(r.db,`publicLiveBuses/${bus.id}`), meta=r.ref(r.db,`liveBusMeta/${bus.id}`); const claim=await r.runTransaction(lock,(v:unknown)=>{ const existing=v && typeof v === 'object' ? v as {uid?:unknown;startedAt?:unknown} : null; const stale=typeof existing?.startedAt === 'number' && Date.now()-existing.startedAt > 120_000; return !existing || existing.uid===user.uid || stale ? {uid:user.uid,startedAt:Date.now()}:undefined; });if(!claim.committed)throw new Error("This bus is already controlled by another driver.");
 let stopped=false,watch:number|undefined,publishing=false,latest=initial; const publish=async()=>{if(stopped||publishing)return;publishing=true;try{const check=await readAssignment(user.uid);if(!check||check.busId!==bus.id){onError("Your administrator changed the assignment; tracking stopped.");await stop();return;}const data={latitude:latest.latitude,longitude:latest.longitude,accuracyMeters:latest.accuracyMeters,active:true,lastUpdated:r.serverTimestamp(),...(latest.speedMps!==undefined?{speedMps:latest.speedMps}:{}),...(latest.headingDeg!==undefined?{headingDeg:latest.headingDeg}:{})};await r.update(r.ref(r.db, "/"),{[`publicLiveBuses/${bus.id}`]:data,[`liveBusMeta/${bus.id}`]:{driverUid:user.uid,active:true,lastUpdated:r.serverTimestamp()}}); await processGeofences(r,bus.id,latest);}catch(e){onError(e instanceof Error?`Firebase write failed: ${e.message}`:"Firebase could not save GPS.");}finally{publishing=false;}};
 const stop=async()=>{if(stopped)return;stopped=true;if(watch!==undefined)navigator.geolocation.clearWatch(watch);try{await r.onDisconnect(lock).cancel();await r.onDisconnect(publicLive).cancel();await r.onDisconnect(meta).cancel();await r.update(r.ref(r.db, "/"),{[`publicLiveBuses/${bus.id}/active`]:false,[`liveBusMeta/${bus.id}/active`]:false,[`activeDrivers/${bus.id}`]:null});}catch{/* best effort */}};
 try{await r.onDisconnect(lock).remove();await r.onDisconnect(publicLive).update({active:false,lastUpdated:r.serverTimestamp()});await r.onDisconnect(meta).update({active:false,lastUpdated:r.serverTimestamp()});await publish();watch=navigator.geolocation.watchPosition(p=>{if(stopped)return;try{latest=location(p);onPosition(latest);void publish();}catch(e){onError(e instanceof Error?e.message:"Invalid GPS.");}},e=>!stopped&&onError(message(e)),options);return {busId:bus.id,stop};}catch(e){await stop();throw e;}
}
