import { useEffect, useState } from "react";
import { LogIn, MapPin, Radio, ShieldCheck } from "lucide-react";
import { getFirebaseRuntime } from "../config/firebase";
import { getDriverAssignment, getLocationSupportMessage, loadDriverProfile, saveDriverName, signInDriver, signOutDriver, startDriverTracking, toDriverLocation, type DriverLocation, type DriverProfile, type DriverTrackingSession } from "../services/driverTrackingService";
import { readBus, type Assignment, type BusConfig } from "../services/fleet";
function browserError(error: GeolocationPositionError) { switch(error.code) { case error.PERMISSION_DENIED:return "Location permission was denied by the browser. Allow location for this site in browser settings, then try again."; case error.POSITION_UNAVAILABLE:return "Your device cannot determine a location right now. Check Location Services."; case error.TIMEOUT:return "The location request timed out. Try again with a clearer view of the sky."; default:return error.message||"The browser could not get a location."; } }
export function DriversPage(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[uid,setUid]=useState<string|null>(null),[profile,setProfile]=useState<DriverProfile|null>(null),[assignment,setAssignment]=useState<Assignment|null>(null),[bus,setBus]=useState<BusConfig|null>(null),[name,setName]=useState(""),[position,setPosition]=useState<DriverLocation|null>(null),[session,setSession]=useState<DriverTrackingSession|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let off:undefined|(()=>void);void getFirebaseRuntime().then(r=>{off=r.onAuthStateChanged(r.auth,u=>setUid(u?.uid??null));}).catch(e=>setMessage(e instanceof Error?e.message:"Firebase unavailable."));return()=>off?.();},[]);
 useEffect(()=>{if(!uid)return;let canceled=false;void Promise.all([loadDriverProfile(uid),getDriverAssignment(uid)]).then(async([p,a])=>{if(canceled)return;setProfile(p);setName(p?.displayName??"");setAssignment(a);setBus(a?await readBus(a.busId):null);}).catch(e=>setMessage(e instanceof Error?e.message:"Could not load driver data."));return()=>{canceled=true;};},[uid]);
 useEffect(()=>{if(!uid)return;let off:undefined|(()=>void);void getFirebaseRuntime().then(r=>{off=r.onValue(r.ref(r.db,`assignments/${uid}`),async snap=>{const next=snap.exists()?snap.val() as Assignment:null;setAssignment(next);setBus(next?await readBus(next.busId):null);if(session&&next?.busId!==session.busId){await session.stop();setSession(null);setMessage("Assignment changed; tracking stopped.");}});});return()=>off?.();},[uid,session]);
 const login=async()=>{setBusy(true);setMessage("");try{await signInDriver(email.trim(),password);setPassword("");}catch(e){setMessage(e instanceof Error?e.message:"Could not sign in.");}finally{setBusy(false);}};
 const saveName=async()=>{if(!uid)return;setBusy(true);try{await saveDriverName(uid,name,email);setProfile(p=>({...p,displayName:name.trim()}));}catch(e){setMessage(e instanceof Error?e.message:"Could not save name.");}finally{setBusy(false);}};
 const stop=async()=>{if(session){await session.stop();setSession(null);setMessage("Tracking stopped and the public bus location was marked inactive.");}};
 const start=()=>{if(!bus||!assignment)return;const support=getLocationSupportMessage();if(support){setMessage(support);return;}setBusy(true);setMessage("Waiting for the browser location prompt…");
 // Keep this exact direct device request before any auth/database/network work.
 navigator.geolocation.getCurrentPosition(async raw=>{try{const initial=toDriverLocation(raw);setPosition(initial);const next=await startDriverTracking(bus,assignment,initial,setPosition,setMessage);setSession(next);setMessage(`Bus ${bus.busNumber} is live and synced to the public tracker.`);}catch(e){setMessage(e instanceof Error?e.message:"Could not begin tracking.");}finally{setBusy(false);}},error=>{setMessage(browserError(error));setBusy(false);},{enableHighAccuracy:true,maximumAge:1_000,timeout:20_000});};
 const logout=async()=>{await stop();await signOutDriver();setProfile(null);setBus(null);setAssignment(null);};
 if(!uid)return <main className="simple-driver-page"><section className="simple-driver-card"><p className="simple-driver-eyebrow">DRIVER CONTROL</p><h1>Driver sign in</h1><form className="simple-driver-form" onSubmit={event=>{event.preventDefault();void login();}}><label>Email<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="simple-driver-button" type="submit" disabled={busy||!email||!password}><LogIn size={18}/>{busy?"Signing in…":"Sign in"}</button></form>{message&&<div className="simple-driver-status error">{message}</div>}</section></main>;
 if(!profile?.displayName)return <main className="simple-driver-page"><section className="simple-driver-card"><p className="simple-driver-eyebrow">WELCOME</p><h1>What&apos;s your full name?</h1><label className="simple-driver-bus">Full name<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>{message&&<div className="simple-driver-status error">{message}</div>}<button className="simple-driver-button" disabled={busy||name.trim().length<2} onClick={()=>void saveName()}>{busy?"Saving…":"Save name"}</button></section></main>;
 return <main className="simple-driver-page"><section className="simple-driver-card"><div className="simple-driver-header"><div><p className="simple-driver-eyebrow">DRIVER CONTROL</p><h1>Live location</h1><p className="simple-driver-description">{profile.displayName}</p></div><button className="simple-driver-link-button" onClick={()=>void logout()}>Sign out</button></div>{profile.enabled===false?<div className="simple-driver-status error">Your driver account is disabled.</div>:!bus||!bus.enabled?<div className="simple-driver-empty">An administrator needs to assign you an enabled bus.</div>:<><div className="simple-driver-bus">Assigned bus<strong>Bus {bus.busNumber}</strong></div><button className="simple-driver-button" disabled={busy} onClick={()=>session?void stop():start()}>{session?<><Radio size={18}/>Stop Tracking</>:<><MapPin size={18}/>Start Tracking</>}</button></>}{message&&<div className="simple-driver-status">{message}</div>}{position&&<div className="simple-driver-coordinates"><div><span>Latitude</span><strong>{position.latitude.toFixed(6)}</strong></div><div><span>Longitude</span><strong>{position.longitude.toFixed(6)}</strong></div><div><span>Accuracy</span><strong>±{Math.round(position.accuracyMeters)} m</strong></div></div>}<div className="simple-driver-note"><ShieldCheck size={15}/>The first location request is browser-native; after success it is synced to your assigned public bus.</div></section></main>;
}
